source 'https://rubygems.org'

# Runtime dependencies
gem 'rails', '~> 6.0.0'
gem 'bundler', '~> 1.17.3'
gem 'sqlite3', '~> 1.4.0'
gem 'sprockets', '~> 3.7.0'

# Gem under test
gem 'izi_lightup', path: '../../../..'

# Development dependencies
gem 'gemika'
gem 'byebug'
gem 'rake'
gem 'rspec'
gem 'rspec-rails'
gem 'guard-rspec'
gem 'listen', '< 3.3.0'
gem 'rspec-html-matchers'
